#!/usr/bin/env ruby
#adapted from http://book.git-scm.com/5_git_hooks.html
html_path = "rspec_results.html"  
`rspec -f h -o #{html_path} -f p tests/rspec.rb` # run the spec. send progress to screen. save html results to html_path  

# find out how many errors were found  
html = open(html_path).read  
examples = html.match(/(\d+) examples/)[0].to_i rescue 0  
failures = html.match(/(\d+) failures/)[0].to_i rescue 0  
if failures == 0 then
	failures = html.match(/(\d+) failure/)[0].to_i rescue 0  
end
pending = html.match(/(\d+) pending/)[0].to_i rescue 0  

if failures.zero?  
  puts "0 failed! #{examples} run, #{pending} pending"  
  puts "View rspec results at #{File.expand_path(html_path)}"  
  exit 0
else  
  puts "\aDID NOT COMMIT YOUR FILES!"  
  puts "View rspec results at #{File.expand_path(html_path)}"  
  puts  
  puts "#{failures} failed! #{examples} run, #{pending} pending"  
  `open #{html_path}`
  exit 1  
end
